#
#server:
#  port: 0
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/msorder
#    username: root
#    password: root
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#
#  application:
#    name: ORDER-SERVICE
#
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${random.uuid}